packages:
  - packages/*

saveExact: true
engineStrict: true
packageImportMethod: hardlink
lockfileIncludeTarballUrl: true
linkWorkspacePackages: deep
injectWorkspacePackages: true
shamefullyHoist: true
fetchRetries: 15
strictDepBuilds: false
dedupePeers: true
dedupeDirectDeps: true

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

catalogs:
  development:
    astro: 7.3.2
    unocss: 66.10.1
    '@unocss/astro': 66.10.1
